# table_helpers.R — LaTeX emit helpers for manuscript table producers.
#
# Every reported .tex table is regenerated by a producer script
# (extract_full_model_analysis.R, extract_vegetation_coefficients.R,
# analyze_paleo_inversion_models.R, 5b_overfitting_diagnostics.R). These
# helpers wrap knitr::kable so the producer code stays focused on the
# numerical lineage and the .tex output is uniform.
#
# Two emit shapes:
#   emit_standalone_tex()  → table1_, table3_, table4_, ... complete
#                            \begin{table}…\end{table} environments with
#                            caption and label. Drop-in \input{} targets.
#   emit_tabular_fragment() → body-only tabular rows, no table environment.
#                             Used for Table 2 and Table S2 where the .tex
#                             wrapper keeps its landscape / longtable
#                             preamble by hand and \input{}s the fragment.
#
# The autogen banner at the top of every emitted file records its producer and
# makes clear that hand edits will be overwritten by the next pipeline run.

library(knitr)

.AUTOGEN_BANNER <- function(source_script) {
  # Intentionally no timestamp: every `make tables` would flip it and
  # pollute `git diff`. Source script + imperative banner is enough for
  # independent numeric checks and for humans reading a .tex file.
  paste0(
    "% Auto-generated by ", source_script, ".\n",
    "% Do not hand-edit — regenerate via `make tables`.\n"
  )
}

emit_standalone_tex <- function(df,
                                path,
                                caption,
                                label,
                                align = NULL,
                                col.names = NULL,
                                digits = NULL,
                                escape = FALSE,
                                note = NULL,
                                placement = "htbp",
                                centering = TRUE,
                                landscape = FALSE,
                                size_macro = NULL,
                                source_script = NULL) {
  if (is.null(source_script)) {
    source_script <- sub(".*/", "", sys.call(-1)[[1]])
    if (length(source_script) == 0 || source_script == "") {
      source_script <- "<unknown>"
    }
  }

  kable_args <- list(
    x = df,
    format = "latex",
    booktabs = TRUE,
    escape = escape
  )
  if (!is.null(align))     kable_args$align     <- align
  if (!is.null(col.names)) kable_args$col.names <- col.names
  if (!is.null(digits))    kable_args$digits    <- digits

  tabular <- do.call(knitr::kable, kable_args)

  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)

  parts <- c(
    .AUTOGEN_BANNER(source_script),
    if (landscape) "\\begin{landscape}" else NULL,
    sprintf("\\begin{table}[%s]", placement),
    if (centering) "\\centering" else NULL,
    sprintf("\\caption{%s}", caption),
    sprintf("\\label{%s}", label),
    if (!is.null(size_macro)) sprintf("\\%s", size_macro) else NULL,
    as.character(tabular),
    if (!is.null(note)) {
      c("\\begin{minipage}{\\linewidth}",
        "\\vspace{2mm}",
        "\\footnotesize",
        sprintf("\\textit{Note:} %s", note),
        "\\end{minipage}")
    } else NULL,
    "\\end{table}",
    if (landscape) "\\end{landscape}" else NULL
  )

  writeLines(parts, path)
  invisible(path)
}

emit_tabular_fragment <- function(df,
                                  path,
                                  align = NULL,
                                  col.names = NULL,
                                  digits = NULL,
                                  escape = FALSE,
                                  include_header = FALSE,
                                  source_script = NULL) {
  if (is.null(source_script)) {
    source_script <- sub(".*/", "", sys.call(-1)[[1]])
    if (length(source_script) == 0 || source_script == "") {
      source_script <- "<unknown>"
    }
  }

  # Emit rows-only so the wrapper .tex controls the preamble (landscape,
  # longtable, column specs). knitr::kable with booktabs=FALSE and a
  # trivial column spec lets us keep just the body, which we then strip
  # of the opening/closing tabular lines.
  kable_args <- list(
    x = df,
    format = "latex",
    booktabs = FALSE,
    escape = escape
  )
  if (!is.null(align))     kable_args$align     <- align
  if (!is.null(col.names)) kable_args$col.names <- col.names
  if (!is.null(digits))    kable_args$digits    <- digits

  tabular <- as.character(do.call(knitr::kable, kable_args))
  lines <- strsplit(tabular, "\n", fixed = TRUE)[[1]]

  # Drop the first and last lines (\begin{tabular}{...} / \end{tabular})
  # and any \hline rows that knitr adds. The wrapper supplies its own rules.
  keep <- !grepl("^\\\\(begin|end)\\{tabular\\}", lines) &
          !grepl("^\\\\hline\\s*$", lines)
  body <- lines[keep]

  # By default drop the header row so the wrapper .tex owns its own
  # (often multi-line) header. The header is always the first non-empty
  # data row knitr emits before any data body rows; it ends in `\\`.
  if (!include_header) {
    first_row <- which(grepl("\\\\\\\\\\s*$", body))[1]
    if (!is.na(first_row)) body <- body[-seq_len(first_row)]
  }

  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(c(.AUTOGEN_BANNER(source_script), body), path)
  invisible(path)
}
